# Generated by Django 5.0.4 on 2024-04-20 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='reting',
            field=models.FloatField(null=True),
        ),
    ]
