# Generated by Django 5.0.4 on 2024-04-20 18:29

import course.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_alter_course_reting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(upload_to=course.helpers.SaveMediaFiles.speciality_image_path),
        ),
        migrations.AlterField(
            model_name='speciality',
            name='image',
            field=models.ImageField(upload_to=course.helpers.SaveMediaFiles.speciality_image_path),
        ),
    ]
