# Generated by Django 5.0.4 on 2024-04-20 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_alter_course_image_alter_speciality_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('df', 'draft'), ('pb', 'published')], default='df', max_length=25),
        ),
    ]
