# Generated by Django 5.0.4 on 2024-04-20 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_course_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='slug',
            field=models.SlugField(default=1, max_length=255, verbose_name='Slug'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='price_type',
            field=models.CharField(choices=[('USD', '$'), ('UZS', 'sum')], default='USD', max_length=12),
        ),
    ]
